# Generated by Django 3.0.5 on 2020-04-21 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0002_auto_20200421_1219'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='student',
        ),
        migrations.RemoveField(
            model_name='books',
            name='total',
        ),
        migrations.CreateModel(
            name='BookUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_issue', models.DateField()),
                ('books', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Books')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_app.Student')),
            ],
        ),
    ]
