# Generated by Django 3.0.5 on 2020-04-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0004_auto_20200421_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
