# Generated by Django 3.0.5 on 2020-04-25 16:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('library_app', '0005_books_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='available',
        ),
        migrations.AlterField(
            model_name='books',
            name='title',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='bookuser',
            name='date_of_issue',
            field=models.DateField(default=datetime.datetime(2020, 4, 25, 16, 30, 18, 342260, tzinfo=utc)),
        ),
    ]
